name = "tunnl3d-com"
pages_build_output_dir = "root"
compatibility_date = "2024-01-01"

# Custom domain configuration
# Associates this Pages project with the tunnl3d.com zone
[[pages.deployment.routes]]
pattern = "tunnl3d.com/*"
zone_name = "tunnl3d.com"

[[pages.deployment.routes]]
pattern = "www.tunnl3d.com/*"
zone_name = "tunnl3d.com"
